sudo rm -rf /home/ubuntu/data_input
sudo rm -rf /home/ubuntu/data_analysis
sudo rm -rf /home/ubuntu/trader
sudo rm -rf /home/ubuntu/gui
sudo rm -rf /home/ubuntu/scripts
sudo rm -rf /home/ubuntu/requirements.txt
sudo rm -rf /home/ubuntu/logger.py
sudo rm -rf /home/ubuntu/main.py
sudo rm -rf /home/ubuntu/env.sh
